var Jimp = require("jimp");
var jsonfile = require('jsonfile')
var path = require('path')
var io  = require('socket.io').listen(5001)
var dl  = require('delivery')
const editJsonFile = require("edit-json-file");
//const sharp = require('sharp');
//var lenna1 = Jimp.read("inputImages/close_overview_handle.png")
var globalCloseHandle_Small
var globalCloseHandle_Medium
var globalCloseHandle_Larg
var mainBackgroundImage
var receivedColor
var TargetRepoName

var express = require("express");
var myParser = require("body-parser");
var app = express();

var globalMasker
var globalAppIcon
var globalShadow

const testFolder = './Cloned_Git_Repositories/';
const fs = require('fs');

// Change depending on this Json file
var Json_Configurator = 'config_changer.json'
var Shared_Global_Configuration_Path
var gm = require('gm')
var pixelColor
var appIconName
var text


function fromDir(startPath,filter, socket){

        if (!fs.existsSync(startPath)){
            console.log("no dir ",startPath);
            return;
        }

        var files=fs.readdirSync(startPath);
        for(var i=0;i<files.length;i++){
            var filePath=path.join(startPath,files[i]);
            var stat = fs.lstatSync(filePath);
            if (stat.isDirectory()){
                fromDir(filePath,filter); //recurse
            } else if (filePath.indexOf(filter)>=0) {
                console.log('-- found: ',filePath);
                io.emit('foundJson', { path : filePath, name : path.basename(filePath)});
            };
        };
};

io.sockets.on('connection', function(socket){

    socket.on('imgBuffer', function (imgBuffer) {
        // My image received by the server here. Do my stuff with image here.
        console.log(imgBuffer);
        // Decoding my Base64 image

        // fs = require('fs');
        // sys = require('sys');
        // string generated by canvas.toDataURL()
        var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0"
            + "NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO"
            + "3gAAAABJRU5ErkJggg==";
        // strip off the data: url prefix to get just the base64-encoded bytes
        var data = img.replace(/^data:image\/\w+;base64,/, "");
        var buf = new Buffer(data, 'base64');
        // console.log(buf)
        //fs.writeFile('image.png', buf);
    })

    socket.on('feedBack', function (obj) {
       var datetime = new Date();
       fs.appendFile('../feedbacks/feedbacks.log', 'Feedback----------------------' + datetime + '\n' +
                                                   'Firstname:' + obj.firstname + '\n' +
                                                   'Lastname:' + obj.lastname + '\n' +
                                                   'Feedback:' + obj.feedback + '\n\n', function (err) {
         if (err) throw err;
         console.log('Feedback Saved!');
         socket.emit('feedbackSaved');
       });

    })

    socket.on('fetchConfigFile', function (obj) {
          jsonfile.readFile(obj.configPath, function(err, configData) {
              socket.emit('configData', configData);
              console.log(configData)
          })

    })
    socket.on('openThisRepo', function (data) {
                fromDir('Cloned_Git_Repositories/'+data.repoNames,'.json', socket)
     })

     socket.on('saveJsonFile', function(jsonTextArea) {
        console.log(typeof jsonTextArea)
        // Nested function to write the file
        socket.on('pathToJson', function(pathToJson) {
            try {
              fs.unlinkSync(pathToJson) //  Remove the file
              //var json = JSON.stringify(jsonTextArea)
              //fs.writeFile(pathToJson, json, 'utf8');
              fs.writeFileSync(pathToJson, jsonTextArea);
            } catch(err) {
              console.error(err)
            }
        })
        socket.emit('jsonFileSaved')
     })
    var delivery = dl.listen(socket);

    fs.readdir(testFolder, (err, files) => {
        socket.emit('Repositories', files)
    })

    delivery.on('receive.success',function(file){
      var params = file.params;
      appIconName = file.name
      //console.log(appIconName)
      fs.writeFile(file.name,file.buffer, function(err){
        console.log(file.name)
        console.log(file.params)
        if(err){
          console.log('Error: Icon file could not received by the server.');
        }else{
          console.log('Icon file received by the server.');
          changeAppIcon()
        };
      });
    });
});

var port = 8000;
var http = require("http");
var server = http.createServer();
server.on('request', request);
server.listen(port);
console.log('SERVER IS UP...');
function request(request, response) {
    var store = '';
    var object

    request.on('data', function(data) {
        store += data
        object = JSON.parse(store)
        console.log('Data Received!! We Proccess it now!')
    });

    request.on('end', function() {
        receivedColor = parseInt(object.colorShortHex)
        TargetRepoName = object.targetRepo
        console.log(TargetRepoName)
        transparentIconCreator()
        transparentIconCreator()
        var noTag = object.colorNoHashTag
        var moduleBackgroundColor = object.moduleBackgroundColor
        var primaryColorDark = object.primaryColorDark
        var secondaryColor = object.secondaryColor
        var accentColor = object.accentColor
        var textColor = object.textColor
        transparentIconCreator()

        function transparentIconCreator(){
            //Create the background color with HEX code
            Jimp.read("inputImages/yellow.png", function (err, mainBackground) {
                if (err) throw err;
                for (var i= 0 ; i< 800 ; i++){
                    for(var j=0 ; j< 800 ; j++){
                    mainBackground.setPixelColor(receivedColor, i ,j)
                    }
                }
                a()
                function a(){
                    mainBackground.write("inputImages/yellow.png");
                }
            });

            // Opening Close Handle PNG
            Jimp.read("inputImages/close_overview_handle.png", function (err, small_handle) {
                if (err) throw err;
                small_handle.quality(100)
                small_handle.resize(73, 39)

                globalCloseHandle_Small = small_handle
            });

            Jimp.read("inputImages/close_overview_handle.png", function (err, medium_handle) {
                if (err) throw err;
                medium_handle.quality(100)
                medium_handle.resize(146, 78)

                globalCloseHandle_Medium = medium_handle
            });

            Jimp.read("inputImages/close_overview_handle.png", function (err, larg_handle) {
                if (err) throw err;
                larg_handle.quality(100)
                larg_handle.resize(272, 136)

                globalCloseHandle_Larg = larg_handle
            });

            // Mixing close handles with transparent backgrounds
            Jimp.read("inputImages/yellow.png", function (err, transparentCloseIcon_Small) {
                if (err) throw err;
                transparentCloseIcon_Small.resize(88, 44)
                     .quality(100)            // resize
                     .opacity(0.5)
                     .composite( globalCloseHandle_Small, 8, 3 )

                     //iOS
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/ios/close_overview_handle.png")

                     //Android
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/android/resources/icons/close_overview_handle.png")

                     .flip(false, true)

                     //iOS
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/ios/issue_overview_handle.png")

                     //Android
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/android/resources/icons/issue_overview_handle.png");
            });

            Jimp.read("inputImages/yellow.png", function (err, transparentCloseIcon_Medium) {
                if (err) throw err;
                transparentCloseIcon_Medium.resize(176, 88)
                     .quality(100)
                     .opacity(0.5)          // resize
                     .composite(globalCloseHandle_Medium, 16, 6)

                     //iOS
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/ios/close_overview_handle@2x.png")

                     //Android
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/android/resources/icons/close_overview_handle@2x.png")

                     .flip(false, true)

                     //iOS
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/ios/issue_overview_handle@2x.png")

                     //Android
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/android/resources/icons/issue_overview_handle@2x.png");
            });

            Jimp.read("inputImages/yellow.png", function (err, transparentCloseIcon_Larg) {
                if (err) throw err;
                transparentCloseIcon_Larg.resize(264, 132)
                     .quality(100)
                     .opacity(0.5)          // resize
                     .composite(globalCloseHandle_Larg, 0, 0)

                     //iOS
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/ios/close_overview_handle@3x.png")

                     //Android
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/android/resources/icons/close_overview_handle@3x.png")

                     .flip(false, true)

                     //iOS
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/ios/issue_overview_handle@3x.png")

                     //Android
                     .write("Cloned_Git_Repositories/"+TargetRepoName+"/Resources/Modules/epaper/android/resources/icons/issue_overview_handle@3x.png");
            });
        }

        let file = editJsonFile(`Cloned_Git_Repositories/`+TargetRepoName+`/Resources/Modules/shared/configuration/global_config.json`);

        // Set a couple of fields
        file.set("primaryColor", noTag);
        file.set("moduleBackgroundColor", moduleBackgroundColor)
        file.set("primaryColorDark",primaryColorDark)
        file.set("secondaryColor",secondaryColor)
        file.set("accentColor",accentColor)
        file.set("textColor",textColor)

        // Save the data to the disk
        file.save();

        // Reload it from the disk
        file = editJsonFile(`jsOutput/gc.json`, {
            autosave: true
        });

        response.setHeader("Content-Type", "text/json");
        response.setHeader("Access-Control-Allow-Origin", "*");
        response.end(store)
   });
}
